language: go

go:
  - 1.12.x

os:
  - linux
  - osx


matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - GO111MODULE=on go mod vendor

branches:
  only:
    - master

script:
  - if [ -n "$(gofmt -s -l . | grep -v "vendor")" ]; then diff -u <(echo -n) <(gofmt -d $(gofmt -s -l . | grep -v "vendor")); fi
  - go test -v -race -coverprofile=coverage.txt  $(go list ./... | grep -v "/vendor/")

after_success:
  - bash <(curl -s https://codecov.io/bash)
